# parish.config.yaml
name: "Paróquia Imaculada Conceição"
short_name: "Imaculada Conceição"
order: "Ordem dos Frades Menores Capuchinhos (OFM Cap.)"
diocese: "Diocese de Ponta Grossa"
location:
  city: "Ponta Grossa"
  district: "Uvaranas"
  state: "PR"
  timezone: "America/Sao_Paulo"
  adress:
    street: "Av. Gen. Carlos Cavalcanti, 361"
    postal_code: "84030-000"
contact:
  instagram: "@paroquiaimaculadapg"
mass_duration_minutes: 60

i18n:
  default_locale: pt-BR
  locales: [pt-BR]

# Unidades pastorais
unidades:
  - name: "Paróquia Imaculada Conceição"
    type: "matriz"
    slug: "imaculada-conceicao"

  - name: "Capela São Vicente"
    type: "branch"
    slug: "sao-vicente"

  - name: "Capela Divina Pastora"
    type: "branch"
    slug: "divina-pastora"