name = "imaculada-conceicao-uvaranas"
main = ".output/public/_worker.js"
compatibility_date = "2026-05-13"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".output/public"
binding = "ASSETS"
